version: '3.8'

services:
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-reverse-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
